### ISSUE TITLE
_SubComponents directory casing issue

### ISSUE THREAD

**Issue by cmmusni** [JCGonzaga01/jc-react-boilerplate#2]
`import { AboutMe, Skills } from "../_subComponents";`
import { AboutMe, Skills } from "components/_subComponents";

This above lines of code uses small `s` for the sub components directly while the folder name is "_SubComponents".

**Comment by JCGonzaga01** [comment]
@cliffordmusniGithub You might be confused I guess.
This project doesn't have _subComponents.
Can you elaborate more on the issue?
